default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "postgres"

development:
  <<: *default
  database: bugtrackingsystem_development

test:
  <<: *default
  database: bugtrackingsystem_test

production:
  <<: *default
  database: bugtrackingsystem_production
  username: bugtrackingsystem
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
